"""Centralized configuration and environment settings for Enterprise AI Agent."""

from functools import lru_cache
from typing import Optional, Set
from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

SUPPORTED_EMBEDDING_PROVIDERS: Set[str] = {"fastembed", "openai"}


class Settings(BaseSettings):
    """Application settings loaded from environment variables and .env file."""

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
        case_sensitive=False,
    )

    # Core Environment
    app_env: str = Field(
        default="development",
        validation_alias="APP_ENV",
        description="Application runtime environment (development, staging, production, test)",
    )

    # Embedding Configuration
    embedding_provider: str = Field(
        default="fastembed",
        validation_alias="EMBEDDING_PROVIDER",
        description="Active embedding provider ('fastembed' or 'openai')",
    )
    embedding_model: str = Field(
        default="BAAI/bge-small-en-v1.5",
        validation_alias="EMBEDDING_MODEL",
        description="Embedding model name or identifier",
    )
    embedding_dimension: int = Field(
        default=384,
        gt=0,
        validation_alias="EMBEDDING_DIMENSION",
        description="Dimensionality of vectors generated by the embedding model",
    )
    embedding_batch_size: int = Field(
        default=64,
        gt=0,
        validation_alias="EMBEDDING_BATCH_SIZE",
        description="Maximum chunk batch size sent for embedding generation",
    )
    embedding_timeout_seconds: float = Field(
        default=30.0,
        gt=0.0,
        validation_alias="EMBEDDING_TIMEOUT_SECONDS",
        description="Timeout in seconds for embedding generation requests",
    )

    # Optional Provider Credentials
    openai_api_key: Optional[str] = Field(
        default=None,
        validation_alias="OPENAI_API_KEY",
        description="API key for OpenAI services (optional for local fastembed execution)",
    )

    # Infrastructure Placeholders
    database_url: Optional[str] = Field(
        default=None,
        validation_alias="DATABASE_URL",
        description="Relational database connection string",
    )
    qdrant_url: Optional[str] = Field(
        default=None,
        validation_alias="QDRANT_URL",
        description="Qdrant vector database URL",
    )
    qdrant_collection_name: str = Field(
        default="enterprise_knowledge",
        validation_alias="QDRANT_COLLECTION_NAME",
        description="Name of the Qdrant collection for vector storage",
    )
    qdrant_api_key: Optional[str] = Field(
        default=None,
        validation_alias="QDRANT_API_KEY",
        description="Optional API key for Qdrant vector database",
    )
    qdrant_timeout_seconds: float = Field(
        default=10.0,
        gt=0.0,
        validation_alias="QDRANT_TIMEOUT_SECONDS",
        description="Timeout in seconds for Qdrant client operations",
    )
    redis_url: Optional[str] = Field(
        default=None,
        validation_alias="REDIS_URL",
        description="Redis cache connection string",
    )

    @field_validator("embedding_provider", mode="before")
    @classmethod
    def validate_embedding_provider(cls, value: str) -> str:
        """Validate and normalize the embedding provider name."""
        if not isinstance(value, str):
            raise ValueError(f"EMBEDDING_PROVIDER must be a string, got {type(value).__name__}")

        normalized = value.strip().lower()
        if normalized not in SUPPORTED_EMBEDDING_PROVIDERS:
            supported = ", ".join(f"'{p}'" for p in sorted(SUPPORTED_EMBEDDING_PROVIDERS))
            raise ValueError(
                f"Unsupported embedding provider: '{value}'. Supported providers are: {supported}"
            )
        return normalized

    @field_validator("embedding_model")
    @classmethod
    def validate_embedding_model(cls, value: str) -> str:
        """Validate that the embedding model identifier is not empty."""
        if not isinstance(value, str) or not value.strip():
            raise ValueError("EMBEDDING_MODEL cannot be empty or whitespace-only")
        return value.strip()

    @field_validator("qdrant_collection_name")
    @classmethod
    def validate_qdrant_collection_name(cls, value: str) -> str:
        """Validate that the Qdrant collection name is not empty or whitespace-only."""
        if not isinstance(value, str) or not value.strip():
            raise ValueError("QDRANT_COLLECTION_NAME cannot be empty or whitespace-only")
        return value.strip()


@lru_cache()
def get_settings() -> Settings:
    """Return a cached singleton instance of application Settings."""
    return Settings()
